<?php

declare(strict_types=1);
/*
 * This file is part of Crucible.
 *
 * Copyright (c) 2026 Luciano Federico Pereira
 * All rights reserved.
 */

namespace LucianoPereira\Crucible\Dialect\Inline;

use function count;
use function explode;
use function implode;
use function in_array;
use function is_array;
use function preg_match;
use function preg_replace;
use function rtrim;
use function token_get_all;

use const T_COMMENT;
use const T_DOC_COMMENT;
use const T_NAME_QUALIFIED;
use const T_NAMESPACE;
use const T_STRING;
use const T_WHITESPACE;

/**
 * The doctest shadow (D-052): a source file's `@crucible` expressions
 * re-homed into one analyzable PHP file — same namespace, so name
 * resolution matches what the engine compiles at discovery, each
 * expression an arrow-function element of a returned array (used
 * values, nothing for a dead-code rule to dislike). `crucible
 * lint-inline` feeds the shadows to PHPStan and maps every reported
 * line back to the origin through the line table. The extraction
 * grammar is InlineBuilder's, one docblock line at a time, so what
 * runs is exactly what gets analyzed.
 */
final readonly class DoctestShadow
{
    /**
     * @param non-empty-string $content
     * @param array<int, int>  $lines   shadow line => origin line
     * @param positive-int     $count
     */
    private function __construct(
        public string $content,
        public array $lines,
        public int $count,
    ) {}

    public static function fromSource(string $source): ?self
    {
        $tokens    = token_get_all($source);
        $total     = count($tokens);
        $namespace = '';

        /** @var list<array{int, non-empty-string}> $doctests origin line + expression */
        $doctests = [];

        for ($i = 0; $i < $total; $i++) {
            $token = $tokens[$i];

            if (!is_array($token)) {
                continue;
            }

            if ($token[0] === T_NAMESPACE && $namespace === '') {
                for ($j = $i + 1; $j < $total; $j++) {
                    $next = $tokens[$j];

                    if (is_array($next) && (in_array($next[0], [T_WHITESPACE, T_COMMENT, T_DOC_COMMENT], true))) {
                        continue;
                    }

                    if (is_array($next) && ($next[0] === T_STRING || $next[0] === T_NAME_QUALIFIED)) {
                        $namespace = $next[1];
                    }

                    break;
                }

                continue;
            }

            if ($token[0] !== T_DOC_COMMENT) {
                continue;
            }

            foreach (explode("\n", $token[1]) as $offset => $line) {
                if (preg_match(InlineBuilder::DOCTEST, $line, $matches) !== 1) {
                    continue;
                }

                // A one-line docblock leaves its closer on the tag's
                // line — the InlineBuilder rule, verbatim.
                $expression = rtrim((string) preg_replace('~\s*\*/\s*$~', '', $matches[1]));

                if ($expression !== '') {
                    $doctests[] = [$token[2] + $offset, $expression];
                }
            }
        }

        if ($doctests === []) {
            return null;
        }

        $header = [
            '<?php',
            '',
            'declare(strict_types=1);',
            '/* Generated by `crucible lint-inline` — do not edit. */',
            '',
        ];

        if ($namespace !== '') {
            $header[] = 'namespace ' . $namespace . ';';
            $header[] = '';
        }

        $header[] = 'return [';

        $lines = [];
        $body  = [];

        foreach ($doctests as $position => [$originLine, $expression]) {
            $lines[count($header) + $position + 1] = $originLine;
            $body[]                                = '    static fn () => ' . $expression . ',';
        }

        $content = implode("\n", [...$header, ...$body, '];']) . "\n";

        return new self($content, $lines, count($doctests));
    }
}
