<?php

declare(strict_types=1);
/*
 * This file is part of Crucible.
 *
 * Copyright (c) 2026 Luciano Federico Pereira
 * All rights reserved.
 */

/*
 * Rewrites record.php from the live incumbent stack: what phpstan-phpunit
 * and pest-plugin-phpstan say each fixture line's type is. Run after a
 * fixture changes, or to re-record against a newer incumbent — and read
 * the diff, because a changed row is the incumbent moving.
 *
 *     php conformance/probes/30-extension-types/regenerate.php
 */

require __DIR__ . '/probe.php';

$stack = \incumbentStack();

if ($stack['directory'] === null) {
    \fwrite(STDERR, "The incumbent stack is not installed: " . $stack['install'] . "\n");

    exit(2);
}

$result = \analyseFixtures('incumbent');

$lines = ['<?php', '', 'declare(strict_types=1);', '', '/*', ' * Generated by regenerate.php from the live incumbent stack. Do not edit:', ' * a row that looks wrong is a question for the incumbent or the fixture.', ' */', '', 'return ['];

foreach ($result['types'] as $label => $type) {
    $lines[] = '    ' . \var_export($label, true) . ' => ' . \var_export($type, true) . ',';
}

$lines[] = '];';
$lines[] = '';

\file_put_contents(__DIR__ . '/record.php', \implode("\n", $lines));

\printf("Recorded %d types from the incumbent.\n", \count($result['types']));

$missing = \array_diff(\array_values(\fixtureLabels()), \array_keys($result['types']));

if ($missing !== []) {
    \printf("Labels the incumbent reported no type for: %s\n", \implode(', ', $missing));

    exit(1);
}
